services:
  postgres:
    image: 'postgres:16.9-alpine'
    environment:
      - 'POSTGRES_DB=international_iam_platform'
      - 'POSTGRES_PASSWORD=local_password'
      - 'POSTGRES_USER=local_user'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:7.4.2-alpine'
    ports:
      - '6379:6379'
